apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: StatefulSet
metadata:
  name: galtan
  labels:
    app: galtan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: galtan
  serviceName: "galtan"
  template:
    metadata:
      labels:
        app: galtan
    spec:
      containers:
      - name: galtan
        image: gcr.io/spexflix/galtan:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
        resources:
          requests:
            memory: "15Mi"
            cpu: "100m"
          limits:
            memory: "20Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: web
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /healthz
            port: web
          initialDelaySeconds: 15
          timeoutSeconds: 20
          periodSeconds: 15
        env:
        - name: PORT
          value: "8080"
        - name: FILE_PATH
          value: "/storage/results.json"
        volumeMounts:
        - name: storage
          mountPath: /storage
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: galtan
spec:
  selector:
    app: galtan
  type: LoadBalancer
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: web
